- name: Install and configure a PHP
  hosts: webserver
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - role: geerlingguy.php

  tasks:
    - name: Ping the server
      ansible.builtin.ping:
