- name: Using vaults
  hosts: localhost
  gather_facts: false
  vars:
    bd_pass: password
  tasks:
    - name: Display secret password from the first vault
      ansible.builtin.debug:
        var: bd_pass
